### ISSUE TITLE
Support for parachain networks

### ISSUE THREAD

**Issue by totalolage** [stylo-app/stylo#11]
Some Kusama parachains and all Polkadot parachains lack support, or their respective networks are commented out. This makes singing transactions, most pressingly those relating to crowdloan rewards, impossible.

Support should be added for the following:

- [ ] Altair
- [ ] Basilisk
- [ ] Bifrost
- [ ] Bit.Country Pioneer
- [ ] Calamari
- [ ] Crust Shadow
- [ ] Efinity
- [ ] Integritee Network
- [ ] Khala Network
- [ ] KILT Spiritnet
- [ ] Kintsugi BTC
- [ ] Manta
- [ ] Mars
- [ ] Moonriver
- [ ] Parallel
- [ ] Parallel Heiko
- [ ] Picasso
- [ ] PolkaSmith
- [ ] QUARTZ
- [ ] Robonomics
- [ ] SubGame Gamma
- [ ] Unorthodox

**Comment by Tbaut** [comment]
Sure, although this requires time and careful testing. I welcome any PR.
I will add in the next releases the networks that are asked by users that reached out to me, namely Altair, Calamari, Acala, Kilt, Bifrost, and probably others. Note that I will not add Moonriver because the signing curve is different there.

**Comment by Tbaut** [comment]
Closing as I will not blanket add them all. Welcoming any PR or request for a network in particular though.
