### ISSUE TITLE
Add Genshiro & Equilibrium

### ISSUE THREAD

**Issue by maflohr** [stylo-app/stylo#30]
May you add Genshiro & Equilibrium?

**Comment by Tbaut** [comment]
Thanks for the request. Since Parity Signer v5 has been released for Android recently, I will gradually stop adding networks, because this way of doing (manually adding them) is not scalable. Stylo was meant to replace Signer v4, because at the time, Signer was not in a good shape. Now that the team has released an improved version I will only provide minimal maintenance for existing networks. Thanks for your understanding.
