### ISSUE TITLE
Possibility to add new network and update metadata

### ISSUE THREAD

**Issue by eshavkun** [stylo-app/stylo#33]
Currently list of networks and their metadata are hardcoded. Trying to scan QR code with new network information leads to message that it's not supported 'cos it's not safe. However with growing number of substrate netwroks, Stylo wallet is way behind in supporting all (or even most) of them. Metadata changes are also quite often. Therefore it adding custom networks should be supported (maybe as advanced/experimental feature) not to block users from using smaller or newer networks (e.g. for claiming rewards)

**Comment by Tbaut** [comment]
Thanks for the issue. As you can imagine, this is not a small task. The goal of Stylo was to fill the void left by Parity Signer v4, that was not maintained. I think this goal was met and Stylo was the only offline signer available for Kusama and Polkadot parachains when they launched. Since then, Signer v5 has been released with great upgradability features, and although Stylo still has IMHO a better UX, I will not maintained it as actively as I used to.

Stylo is a week-end project, and I'm the only maintainer. Signer on the other hand has a multi-person team behind. I work, and will continue to work together with this team, on my free time, to make Signer even better, but as of now, I will not add any new feature to Stylo. cf https://github.com/stylo-app/stylo/issues/30#issuecomment-1133606009
